import Link from 'next/link'
import Icon from './Icon'

export const identityData = [
  {
    slug: 'artistic-director',
    num: '01',
    icon: 'director',
    emoji: '🎭',
    title: 'Artistic Director',
    sub: 'Direction · Vision · Execution',
    desc: 'Conceiving and orchestrating complete artistic experiences — from concept to curtain call. Every element choreographed to serve a single, unified vision.',
    bg: 'AD',
    color: '#a78bfa',
  },
  {
    slug: 'event-organiser',
    num: '02',
    icon: 'events',
    emoji: '🎪',
    title: 'Event Organiser',
    sub: 'Production · Management · Flow',
    desc: 'Founder of Aurastic Productions. Designing and delivering events as complete atmospheric experiences — sound, light, stage, and emotion, unified.',
    bg: 'EO',
    color: '#818cf8',
  },
  {
    slug: 'dj-dwara',
    num: '03',
    icon: 'dj',
    emoji: '🎧',
    title: 'DJ Dwara',
    sub: 'Sets · Energy · Crowd Reading',
    desc: 'Curating sonic journeys that move crowds. Every set is a live composition — reading the room, building energy, and delivering moments that stay with people.',
    bg: 'DJ',
    color: '#c084fc',
  },
  {
    slug: 'dancer',
    num: '04',
    icon: 'dancer',
    emoji: '💃',
    title: 'Dancer',
    sub: 'Movement · Expression · Performance',
    desc: 'Dance is the most honest form of artistic expression. Through movement, I communicate what words and technology cannot — pure, unfiltered human emotion.',
    bg: 'DA',
    color: '#f0abfc',
  },
  {
    slug: 'ai-ml',
    num: '05',
    icon: 'ai',
    emoji: '🤖',
    title: 'AI & ML',
    sub: 'Intelligence · Systems · Innovation',
    desc: 'Bridging art and artificial intelligence. Building intelligent systems that augment creative production and push the boundary of what events and media can become.',
    bg: 'AI',
    color: '#7dd3fc',
  },
  {
    slug: 'editor',
    num: '06',
    icon: 'editor',
    emoji: '🎬',
    title: 'Editor',
    sub: 'Narrative · Rhythm · Post',
    desc: 'Editing is storytelling in its purest form. Crafting aftermovies, highlight reels, and cinematic pieces that carry the emotional weight of every event forward in time.',
    bg: 'ED',
    color: '#6ee7b7',
  },
  {
    slug: 'designer',
    num: '07',
    icon: 'designer',
    emoji: '✦',
    title: 'Designer',
    sub: 'Visual · Brand · Identity',
    desc: 'Designing visual identities, event creatives, stage aesthetics, and digital experiences that are cohesive, intentional, and impossible to forget.',
    bg: 'DS',
    color: '#fcd34d',
  },
  {
    slug: 'photographer',
    num: '08',
    icon: 'photographer',
    emoji: '📷',
    title: 'Photographer',
    sub: 'Frame · Light · Moment',
    desc: 'Capturing moments that carry the atmosphere of an entire night in a single frame. Candid, cinematic, and always emotionally truthful photography.',
    bg: 'PH',
    color: '#fb923c',
  },
]

export default function Identities() {
  return null
}
